language: python
python:
  - '3.6'
  - '3.7'

install:
  - pip install -U pip

before_script:
  - pip install -r requirements.txt
  - git clone https://github.com/mailgyc/doudizhu.git
  - cd doudizhu

script: 
  - coverage run

after_success:
  - coverage report
