sudo: false
language: python
python:
  - '3.6'
  - '3.5'

install:
  - pip install tox codecov
  - pip install -r requirements.txt

script: pytest

#after_success:
#  - tox -e coverage-report
#  - codecov
