language: python
python:
  - '3.6'

install:
  - pip install -U pip

before_script:
  - pip install -r requirements.txt
  - git clone https://github.com/mailgyc/doudizhu.git
  - cd doudizhu/doudizhu

script: 
  - coverage run __init__.py

after_success:
  - coveralls
